### ISSUE TITLE
Failed to open the serial port plotter

### ISSUE THREAD

**Issue by XQB12138** [yhur/arduplot#15]
` *  正在文件夹 demo3_personal 中执行任务: C:\Users\xiang\.platformio\penv\Scripts\platformio.exe device monitor 

--- serial_plotter is starting
FileNotFoundError: Traceback (most recent call last):
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\platformio\device\monitor\command.py", line 152, in device_monitor_cmd
    start_terminal(options)
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\platformio\device\monitor\terminal.py", line 54, in start_terminal
    term = new_terminal(options)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\platformio\device\monitor\terminal.py", line 102, in new_terminal
    term = Terminal(
           ^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\platformio\device\monitor\terminal.py", line 28, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\serial\tools\miniterm.py", line 403, in __init__
    self.update_transformations()
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\serial\tools\miniterm.py", line 456, in update_transformations
    self.tx_transformations = [t() for t in transformations]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\penv\Lib\site-packages\serial\tools\miniterm.py", line 456, in <listcomp>
    self.tx_transformations = [t() for t in transformations]
                               ^^^
  File "E:\Wenzhou University\Temporary working folder\Project\EXperiment2(piezoelectric)\demo3_personal\monitor\filter_plotter.py", line 52, in __call__
    self.plot = subprocess.Popen([self.arduplot, '-s', str(PORT)])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiang\.platformio\python3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xiang\.platformio\python3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

 *  终端进程“C:\Users\xiang\.platformio\penv\Scripts\platformio.exe 'device', 'monitor'”已终止，退出代码: 1。 
 *  终端将被任务重用，按任意键关闭。 

 *  正在文件夹 demo3_personal 中执行任务: C:\Users\xiang\.platformio\penv\Scripts\platformio.exe device monitor 
`

**Comment by yhur** [comment]
Would you tell me what problem you have in English?
